# Generated by Django 6.0 on 2025-12-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='user@cloud.com', max_length=100)),
                ('mob', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
